//
// Created by Adriano Bacac on 29.05.15.
//
// Creates Graph from input file.
// Supports formats:
//    - ".po" generated by poa.
//
// Example of usage:
// Graph *graph;
// GraphFactory gFactory;
// gFactory.create(
//        "input.po"  // file generated by poa containing all information about graph.
// )
//

#ifndef POA_GRAPHFACTORY_H
#define POA_GRAPHFACTORY_H


#include <string>
#include "Graph.h"

class GraphFactory {
public:
  // Generates graph from input file <path>.
  // Supports formats:
  //    - ".po" generated by poa.
  Graph *Create(std::string path);
};


#endif //POA_GRAPHFACTORY_H
